lenguage: node_js

cache:
  directories: 
    - node_modules
    - ~/.npm

node_js:
  - '15'

git: 
  depth: 3


notifications:
  slack:
    secure: "JKiqivqLpiYRNu/c8xivHd7j7DhUKULFJICDDju2c8E+CaWxwnIwz2j1qUJGiLT8JuPChmVoobl79HglHqc0jI6bQXcQdJt7VXArpxFAhvZz+Y24aqZ2I2DbtKcDlJwz6NF+OAMlbVjkazS6y+oe8n3sFBIjNhd3XiTy9i7nAK0q7dKK4t6PhgqW6Ndz8SXOTW4GsGh74rr5m8xUMlB+vcxb8mNA5D9jMVvL6DgNGnfgKiZzEXD8oaMAyTdCDY/QsdC3q1XtMCQV87jIxPmWIv+fLiBjXWz0KONc2qqecZs5EIJ7GUuFmh+dBb4JJrgAxzitEHSbfApxlHUJeMbptJQcos48xqXUB+6zjxCGyoiaDQVSu1PD/dM1sYg5XJ02lIuLR8PIhxcO2i/jKpQyH3LzvjzPUnzTs8V9SCYp6tf6wgiSbDJK/H289xcqzryt4m1gbCFxwyzpkxyUEbxT29xvM1YEi+F/5CrhP8wFtb0+JVQzVZ9pOM+Gb5zA9X0MR5nYCVOseX51xlR7c5qdrnr3czYot5avqWKDBaSyHR9RHDsOVVLC9h0J6BapzygCyUyGGcrOV94bpFGyLPDtk6wb6jvQe7cHSJJpT2VzUiwokH8swR4D/s0hIEdxdDbWCBhYBMNKrbIkNkNSGp5X9Pp8gDjyX8lmO3v4hkfWBxs=" 

deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: 
    secure: "R4Lhg6910YR6YepjQR42fL3kHAZkxnsdVVS3LjX1Pbna7hLqCPHuo3G5G8KamwIKC8ZsYMqQhPWYZ2sqVQ/1AnV1LsqZyNClaeeTVed+GbjtRxedUubyQJ7GByAECA+Vm79jxPZZi/wzAHlGR7XvKwE+ML+eBeQB2lY/W7CrCDlscxM/PYTre65zb2jKqY4Py/9jlKbyHFUWX+2hauqOS3KFQs6wMty2fPjOz0s1yCJ2zNTr52cTQnT1Fa1LYcO4Xu1E/zF+L4UCW4DPAYaPN3zh6/5iioholn923h+hli565LTo0VgZMJT6nGmrwC98RyQ8s9+Qj5EUO/HVfJR32+/rbqpqWnOM7cFNpgD5PugVpaDAzU8CPDw0vTrpojM8G123k9RA3ul0FLuQTLbjuaOexsIruegUbCFrD9KNzfMge4pcxtU9/MW1nxsYb/uz1pJy++xs3UTKSpP6/sEZPZ6GOSnZFH85V17gyBf9ouvj2MNsG+diQnujxUEmIGHe9onhGXYSBQhCqECc5AmHw2HM1269OekV6HypHA2oKRDCxROEIoTaCNXseW8bV8rNaVZ32ty1olOAXaJLDhmx+RDod0XJm46e636CiPahY1ps61hl1ArKjaZUraZgdNmTHP96n519gLUGqJucCHQ6GnpyVJuj1ZqCaoSYbQb/B5M="
  app: continuous-integration
  on: 
    repo: ClariseT/Beweis
    branch: main
