lenguage: node_js

cache:
  directories: 
    - node_modules
    - ~/.npm

node_js:
  - '15'

git: 
  depth: 3


notifications:
  slack:
    secure: "H5rB3KTO1SaB3r/Aauj9sXXZTwtldWxsCFJZhRKiJaORsp+KOCJLccNxRIqJ7lDCOpGh3EWB02aWluKDLThgY9Q//MjKVF26wHm5JlLd2rxyHJJOj2pzqXGLKNed6eG6qiSxmw4u6ra/u0LUZnjuqKroqNF3byQfNQzfWE8mN2LpD4C9hsmr2SughcHEaRhLcUZyL29vC/F+wiTsC7C0LiR1jHelBwyv2TP0gB7k0iG1dlJQAYugQc00S70eF+lKvazxislgIiLuL2BwqlaFo5evg1l7VnSjfJYceNPRUnxBKKoXK4lM5MYtVv/BlFtFEy26z+4DDoDg/Lt79LDctY/AKyN189r/JZEdYML/90ZoDWcipO8V18rugQIPTPvsgPSl8c/6JRUQesHiGMhW9LkXT6BhVLYyPG8PhuOPrgFCR1vfX8xV2q81uBsKbzRGwv6ixgRs7thtagXZxVHAayKUi6aQLFWVgFXOr1FQgdlKWi4Blzdbt3JaFoDwfFceRH2ArEiV0fmswY6QzdURjKTXPgrx6FQbGAKMPn72x6r6hFwq9a8LFbuxrAFyOZUuqiVqXvWBFfoO5bm2qQLmfFzcCycbEkEgbkhQouj4fJGl4fyDm9sBqm9dAC0jM4IeFhOXP3/dTEyWpL91keh+LEa7rdCgln/4nX0F6JO0VyE=" 

deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: 7748cc9b-8eb6-4a2a-ab71-669d93a0c197
  app: continuous-integration
  on: 
    repo: ClariseT/Beweis
    branch: main
